### ISSUE TITLE
which version of numpy it shoud be?

### ISSUE THREAD

**Issue by SeekPoint** [ApoGouv/Big-Data-Link-Prediction#3]
mldl@ub1604:~/ub16_prj/Big-Data-Link-Prediction/src$ python predictions_with_GBC.py 
 /!\ Script Starting execution @:  09:02:43  /!\ 
****  LOADED: training_features_scaled
Traceback (most recent call last):
  File "predictions_with_GBC.py", line 17, in <module>
    labels_array = np.loadtxt('out-after-features/labels_array.txt', dtype=int)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1024, in loadtxt
    items = [conv(val) for (conv, val) in zip(converters, vals)]
ValueError: invalid literal for long() with base 10: '0.000000000000000000e+00'
mldl@ub1604:~/ub16_prj/Big-Data-Link-Prediction/src$

**Comment by SeekPoint** [comment]
labels_array = np.loadtxt('out-after-features/labels_array.txt', dtype=dtype=np.float64)

that 's my workaround
